version: "3.4"
services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq-node-notifier'
    ports:
        - 5673:5672
        - 15673:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_nodejs
  publisher:
    build:
      context: ./backend
      target: dev
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- node  src/backend/build/examples/notifier/notify.js'
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - rabbitmq_nodejs
  consumer:
    build:
      context: ./backend
      target: dev
    volumes:
      - .:/src
    depends_on:
      - "rabbitmq"
    environment:
      AMQP_URL: amqp://guest:guest@rabbitmq:5672
    ports:
      - 3000:3000
    networks:
      - rabbitmq_nodejs
  vue-ui:
    build:
      context: ./ui
    ports:
      - "8080:8080"
    container_name: ui
    volumes:
       - ./ui:/usr/src/app/ui
       - /usr/src/app/ui/node_modules

networks:
  rabbitmq_nodejs:
    driver: bridge
